### ISSUE TITLE
Zoekgame online

### ISSUE THREAD

**Issue by seppevs162** [Broeders-Handel/NetworkGame1920#23]
zoek al een game die we willen toevoegen

**Comment by Imm0rtall420** [comment]
Vier op een rij gevonden, ik ben nu deze aan het proberen maken.

**Comment by Hoofkoen** [comment]
Waarom is deze gesloten? Waar is de conclussie?
Ik krijg van SImon de vraag om op branch 23 te kijken... Waarom bestaat er nog een branch gelinkt aan dit issue als het al gesloten is?

**Comment by Hoofkoen** [comment]
@Imm0rtall420 mag dit gesloten worden?

**Comment by Imm0rtall420** [comment]
We hebben de game gevonden namelijk voor op een rij.
