### ISSUE TITLE
User verwijderen na disconnecten

### ISSUE THREAD

**Issue by seppevs162** [Broeders-Handel/NetworkGame1920#30]
Als de user disconnect, staat hij nog in de list. De user moet verwijderd worden uit de list na het diconnecten

**Comment by Hoofkoen** [comment]
Waarom is dit gesloten? Is er een conclussie? Een antwoord?

**Comment by Hoofkoen** [comment]
gelinkt aan #39 ?

**Comment by JansegersEli** [comment]
issue opgelost zie #39
