### ISSUE TITLE
Fout Grid oplossen game

### ISSUE THREAD

**Issue by Imm0rtall420** [Broeders-Handel/NetworkGame1920#36]

**Comment by Imm0rtall420** [comment]
null exception vanaf de namen worden ingevuld.

**Comment by Imm0rtall420** [comment]
De usercontrol in de game wilt niet werken hierdoor werkt de mainform voor de game te spelen niet, ik probeer nu een alternatief te vinden.

**Comment by Hoofkoen** [comment]
Waarom heb je de namespace van het grid verwijderd? Daardoor is de link kapot...

1. Als je een project van internet plukt is het de bedoeling om dit ook zelf te kunnen integreren. Verwacht niet dat ik dit voor jullie ga doen.
2. 4 op een rij is nu geen moeilijk spel... Waarom maak je dit niet simpelweg zelf?
3. Werk meteen in de client (IN AFZONDERLIJKE KLASSEN) zodat je later geen tijd moet verdoen met dit over te zetten... Begin met simpelweg ergens op het raster een bol te kunnen zetten. Pas daarna stop je er de logica in van het spel zelf!

**Comment by Imm0rtall420** [comment]
Ik laat de grid even achter en ik maak een nieuwe issue aan zodat de gebruiker zelf al eerst via een command de GameForm al kan openen --> issue 41

**Comment by Hoofkoen** [comment]
NvT
