### ISSUE TITLE
Zelfde Username connect wel nog

### ISSUE THREAD

**Issue by seppevs162** [Broeders-Handel/NetworkGame1920#37]
Als 2 keer dezelfde username wordt geconnect komt er een foutmelding op maar connecteren allebei de clients nog

**Comment by seppevs162** [comment]
Nu moet je een andere gebruikersnaam opgeven, maar hij toont wel nog de eerste gebruikersnaam die je opgaf bij het joinen

**Comment by Hoofkoen** [comment]
UsersController.addUser(username, client)
Hier controleren of username al bestaat
als username al bestaat => return nothing => antwoord naar client
als username nog niet bestaat => maak aan, voeg toe en geef terug => antwoord naar iedereen


Dim User As New Users(username, client) wordt tweemaal uitgevoerd
