### ISSUE TITLE
User verwijderen na disconnecten

### ISSUE THREAD

**Issue by JansegersEli** [Broeders-Handel/NetworkGame1920#39]

**Comment by Hoofkoen** [comment]
Voeg een beschrijving toe WAT je wilt bereiken met dit issue... Is dit een fout? Is dit een toevoeging? Maak het duidelijk voor externe partijen (ik dus)

**Comment by Hoofkoen** [comment]
Dictionary aanpassen naar String-Object

**Comment by Hoofkoen** [comment]
1. Client
disconnecteren zodat je terug in startsituatie zit

2. Server
User verwijderen uit lijsten

**Comment by Hoofkoen** [comment]
Stand van zaken?
zie #42  ?

**Comment by JansegersEli** [comment]
Als de client nu op disconnect klikt dan zal hij een bericht versturen naar de server met daar in het nieuwe Disconnect command. De server zal nu dan die specifieke client verwijderen uit de lijst met clients en als de client nu een bericht wil sturen dan zal die een bericht krijgen dat dit niet meer mogelijk is want hij is niet verbonden met de server. 

Ook kan je nu opnieuw connecten nadat je bent gedisconnect , dit heb ik gedaan door de vorige thread te vervangen door een nieuwe thread die wordt aangemaakt na het disconnecten van de vorige user.
