### ISSUE TITLE
Challenge functie kan nog niet redirecten naar de ReadyForm

### ISSUE THREAD

**Issue by Imm0rtall420** [Broeders-Handel/NetworkGame1920#41]
In de chatclient heb staat er nieuwe functie Challenge, hierbij wil ik ervoor zorgen dat de client met een command naar de readyform kan gaan maar ik kan nog niet redirecten naar de form.

**Comment by Hoofkoen** [comment]
- Geef aan server door met **wie** op basis van username
- Speel het spel in hetzelfde formulier (kan later nog aangepast worden)

**Comment by Hoofkoen** [comment]
Geen readyform
