### ISSUE TITLE
Disconnect button bij fout dubbele username

### ISSUE THREAD

**Issue by ll-28441** [Broeders-Handel/NetworkGame1920#43]
Na dat je de fout melding van duplicate username krijgt moet je op de disconnect knop duwen voor je kan connecten. Hier zou je gewoon direct op connect moeten kunnen duwen.

**Comment by Hoofkoen** [comment]
Of nog beter, meteen de vraag krijgen voor een andere gebruikersnaam...

**Comment by Hoofkoen** [comment]
als geen gebruikersnaam wordt ingegeven => terug naar startscherm (met 'connect' button)

**Comment by Hoofkoen** [comment]
#35

**Comment by ll-28441** [comment]
Issue alleen nog maar opgelost als de username niets is, moet nu nog kijken voor dubbele username.

**Comment by ll-28441** [comment]
Issue opgelost ik kan nu gewoon meteen een andere username ingeven en connecten.

**Comment by Hoofkoen** [comment]
Test dit ook bij opeenvolgend verkeerde ingaves

**Comment by ll-28441** [comment]
Heb dit getest en werkt ook nog na meerdere keren dezelfde naam in te vullen.

**Comment by Hoofkoen** [comment]
En hoe kan je annuleren?

**Comment by Hoofkoen** [comment]
Zorg dat bij het ingeven van een lege username de client alle connectie met de server verbreekt

**Comment by Hoofkoen** [comment]
See commit
