### ISSUE TITLE
Show connected clients

### ISSUE THREAD

**Issue by Hoofkoen** [Broeders-Handel/NetworkGame1920#44]
Show all clients connected to server
update when client connects / disconnects

**Comment by Imm0rtall420** [comment]
er is een thread fout bij de server als ik een client wil toevoegen in de listbox
dit is een fout bij de #36 branch
![errorr](https://user-images.githubusercontent.com/55586863/79984879-13388780-84aa-11ea-8b13-4ae46a3873f5.PNG)

**Comment by Hoofkoen** [comment]
Is er iemand op de master aan het werken?
Seppe?

**Comment by Imm0rtall420** [comment]
neen niemand is op de master aan het werken.
groetjes Simon

**Comment by Hoofkoen** [comment]
Hoor dan eens bij Seppe, die heeft dezelfde fout

**Comment by JansegersEli** [comment]
Ik krijg ook mijn lijst niet in de Listbox op de client , er gebeurt gewoon niets.

**Comment by Hoofkoen** [comment]
Waar wordt deze fout gegooid?
De GUI wordt aangemaakt in de main thread. Het luisteren naar de server gebeurt in en andere. Deze fout geeft aan dat je vanuit een andere thread een GUI element uit de main thread wilt aanspreken (juist zoals de berichten die je binnenkrijgt bij de chat).
Probeer van die code te stelen

**Comment by Imm0rtall420** [comment]
De clients worden in zowel de server als in de client form getoond.
het programma werkt nu.

**Comment by JansegersEli** [comment]
Showed nog niet de clients , werkt dus nog niet

**Comment by Hoofkoen** [comment]
solution see #48
