### ISSUE TITLE
create private chatbox

### ISSUE THREAD

**Issue by Hoofkoen** [Broeders-Handel/NetworkGame1920#45]
Blocked by #44 

private message based on username

GUI
* all in 1 main form
* create subform for each 'chatroom'
* Use 'tabpages'

To be discussed?
=> 19/4/2020 decission!

**Comment by seppevs162** [comment]
De client is apart en als je iemand uitdaagt dan ga je in de gameform en dan gebruiken we tabpages voor main lobby en private chat.

**Comment by JansegersEli** [comment]
Er is nu de mogelijkheid om een private chat te maken met 1 andere client. er is momenteel wel maar 1 chatroom.

**Comment by JansegersEli** [comment]
Ik heb nog geen manier om te kijken welke user er bij welke chatID hoort door middel van een username

**Comment by Hoofkoen** [comment]
1) property PrivateChatBox property in User 
2) property invullen in constructor PrivateChatroom

11 => user1.PrivateChatbox = Me (property as PrivateChatroom)
user2.PrivateChatbox = Me
OF
11 => user1.PrivateChatboxId = ID (property as Integer)
user2.PrivateChatboxId = ID (property as Integer)

3) Bij inkomend privaat bericht op basis van username User ophalen
4) van user private chatbroom ophalen
5) bericht versturen naar private chatroom

**Comment by JansegersEli** [comment]
Private Messages werken nu en het is naar de master gepushed

**Comment by Hoofkoen** [comment]
Is dit afdoende getest? Lees: door iemand anders? Enkel dan kan je zeker
zijn dat het foutvrij is...


Op do 14 mei 2020 om 20:54 schreef JansegersEli <notifications@github.com>:

**Comment by Hoofkoen** [comment]
Branch mag verwijderd worden @JansegersEli
