### ISSUE TITLE
Write en Disconnect functie in een aparte sub

### ISSUE THREAD

**Issue by JansegersEli** [Broeders-Handel/NetworkGame1920#46]
Maakt een aparte sub voor messages en commands

**Comment by Hoofkoen** [comment]
Zorg ervoor dat elk inkomend bericht wordt onderzocht naar een commando
* //MSG//
* //DISC//
* .....

![image](https://user-images.githubusercontent.com/55586772/80275401-37ca7480-86e1-11ea-91a7-1578cb62639f.png)

**Comment by JansegersEli** [comment]
Dat onderzoeken naar een commando, bedoelt u dan server side of client side?

**Comment by JansegersEli** [comment]
Meneer weet u waarom ik deze foutmelding krijg want de user zit in de dictionary
![image](https://user-images.githubusercontent.com/55586887/80735531-233b1180-8b11-11ea-9e38-d3c9cf67354d.png)

**Comment by Hoofkoen** [comment]
@JansegersEli  Test dit nog eens, en dan kan je naar de master mergen
