### ISSUE TITLE
Privaat gesprek met bezet persoon afblokken

### ISSUE THREAD

**Issue by Hoofkoen** [Broeders-Handel/NetworkGame1920#57]
Voorzie correcte melding als tweede persoon reeds in privaat gesprek is..

**Comment by JansegersEli** [comment]
Je kan geen private gesprek starten met een persoon die bezet is door de property IsBusy en je kan ook geen private gesprek starten met jezelf

**Comment by seppevs162** [comment]
Getest en werkt
